name: "Ruby on Rails CI/CD"

on:
  push:
    branches:
      - "*" 
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: hash_pick_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      redis:
        image: redis:4.0
        ports:
          - "6379:6379"

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/hash_pick_test"
      REDIS_URL: "redis://localhost:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.5'
          bundler-cache: true
          
      - name: Install dependencies
        run: 
          bundle install
        shell: bash

      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
