name: "Ruby on Rails CI/CD"
on:
  push:
    branches:
      - "*" 
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: hash_pick_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      redis:
        image: redis:4.0
        ports:
          - "6379:6379"

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/hash_pick_test"
      REDIS_URL: "redis://localhost:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.5'
          bundler-cache: true

      - name: Install Postgres Client
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: 
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
        # Add or replace test runners here
      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.5'
          bundler-cache: true

      - name: Install Postgres Client
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: 
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
